/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carreravehiculosproject;

/**
 *
 * @author camil
 */
import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Random;

public class CarreraForm extends javax.swing.JFrame {
    private static final int NUM_VEHICULOS = 10;
    private List<Vehiculo> vehiculos;
    private javax.swing.Timer timer;
    private boolean corriendo = false;
    private double tiempoSim = 0.0;
    private int terminados = 0;
    private int apuesta = -1;
    
    public CarreraForm() {
        initComponents();
        inicializarCarrera();
    }
    
    private void inicializarCarrera() {
        vehiculos = new ArrayList<>();
        for (int i = 0; i < NUM_VEHICULOS; i++) {
            vehiculos.add(new Vehiculo(i));
            jComboBoxApuesta.addItem("Vehículo " + (i + 1));
        }

        // Timer que actualiza la carrera
        timer = new javax.swing.Timer(20, e -> tick());
    }
    private void tick() {
        if (!corriendo) return;

        double factor = jSliderVelocidad.getValue() / 100.0;
        double delta = timer.getDelay() / 1000.0 * factor;
        tiempoSim += delta;

        int metaX = jPanelPista.getWidth() - 40;

        for (Vehiculo v : vehiculos) {
            if (!v.terminado) {
                v.x += v.velocidad * delta;
                if (v.x >= metaX) {
                    v.terminado = true;
                    v.tiempoFinal = tiempoSim;
                    terminados++;
                }
            }
        }

        jPanelPista.repaint();

        if (terminados >= NUM_VEHICULOS) {
            timer.stop();
            corriendo = false;
            mostrarResultados();
        }
    }
    private void mostrarResultados() {
        List<Vehiculo> ordenados = new ArrayList<>(vehiculos);
        ordenados.sort(Comparator.comparingDouble(v -> v.tiempoFinal));

        StringBuilder sb = new StringBuilder("Resultados:\n");
        for (int i = 0; i < ordenados.size(); i++) {
            Vehiculo v = ordenados.get(i);
            sb.append((i + 1)).append(") Vehículo ").append(v.id + 1)
              .append(" - ").append(String.format("%.2f s", v.tiempoFinal)).append("\n");
        }

        String ganador = "Ganador: Vehículo " + (ordenados.get(0).id + 1);
        if (apuesta >= 0) {
            if (apuesta == ordenados.get(0).id) {
                ganador += "\n¡Tu apuesta ganó!";
            } else {
                ganador += "\nTu apuesta perdió.";
            }
        }

        JOptionPane.showMessageDialog(this, sb.toString() + "\n" + ganador);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelPista = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2 = (Graphics2D) g;

                // fondo
                g2.setColor(Color.WHITE);
                g2.fillRect(0, 0, getWidth(), getHeight());

                // dibujar los carros con etiquetas
                if (vehiculos != null) {
                    for (Vehiculo v : vehiculos) {
                        // círculo del carro
                        g2.setColor(Color.getHSBColor((float) v.id / NUM_VEHICULOS, 0.8f, 0.9f));
                        g2.fillOval((int) v.x, (int) v.y, 20, 20);

                        // etiqueta con el número del carro
                        g2.setColor(Color.BLACK);
                        g2.drawString("Carro " + (v.id + 1), (int) v.x, (int) v.y - 5);
                    }
                }
            }
        };
        jComboBoxApuesta = new javax.swing.JComboBox<>();
        jButtonApostar = new javax.swing.JButton();
        jButtonIniciar = new javax.swing.JButton();
        jButtonReiniciar = new javax.swing.JButton();
        jSliderVelocidad = new javax.swing.JSlider();
        jLabelEstado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPista.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout jPanelPistaLayout = new javax.swing.GroupLayout(jPanelPista);
        jPanelPista.setLayout(jPanelPistaLayout);
        jPanelPistaLayout.setHorizontalGroup(
            jPanelPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelPistaLayout.setVerticalGroup(
            jPanelPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        jComboBoxApuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxApuestaActionPerformed(evt);
            }
        });

        jButtonApostar.setText("Apostar");
        jButtonApostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApostarActionPerformed(evt);
            }
        });

        jButtonIniciar.setText("Iniciar");
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });

        jButtonReiniciar.setText("Reiniciar");
        jButtonReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReiniciarActionPerformed(evt);
            }
        });

        jLabelEstado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelEstado.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSliderVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonReiniciar)
                            .addComponent(jButtonIniciar)
                            .addComponent(jComboBoxApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonApostar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                        .addComponent(jLabelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jComboBoxApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonApostar)
                    .addComponent(jLabelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonIniciar)
                .addGap(18, 18, 18)
                .addComponent(jButtonReiniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSliderVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxApuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxApuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxApuestaActionPerformed

    private void jButtonApostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApostarActionPerformed
        if (corriendo) return;
        apuesta = jComboBoxApuesta.getSelectedIndex();
        jLabelEstado.setText("Apostaste al Vehículo " + (apuesta + 1));
    }//GEN-LAST:event_jButtonApostarActionPerformed

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        if (corriendo) return;

        Random rnd = new Random();
        int alto = jPanelPista.getHeight();
        for (int i = 0; i < vehiculos.size(); i++) {
            Vehiculo v = vehiculos.get(i);
            v.x = 10;
            v.y = 30 + i * (alto / NUM_VEHICULOS);
            v.velocidad = 50 + rnd.nextDouble() * 150;
            v.terminado = false;
            v.tiempoFinal = Double.POSITIVE_INFINITY;
        }

        tiempoSim = 0;
        terminados = 0;
        corriendo = true;
        timer.start();
        jLabelEstado.setText("¡Carrera en curso!");
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    private void jButtonReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReiniciarActionPerformed
        timer.stop();
        corriendo = false;
        tiempoSim = 0;
        terminados = 0;
        apuesta = -1;
        jLabelEstado.setText("Listo para apostar.");
        jPanelPista.repaint();
    }//GEN-LAST:event_jButtonReiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // --- Clase Vehiculo ---
    static class Vehiculo {
        int id;
        double x, y, velocidad;
        boolean terminado;
        double tiempoFinal;

        Vehiculo(int id) {
            this.id = id;
            this.x = 10;
            this.y = 0;
            this.velocidad = 0;
            this.terminado = false;
            this.tiempoFinal = Double.POSITIVE_INFINITY;
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CarreraForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonApostar;
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JButton jButtonReiniciar;
    private javax.swing.JComboBox<String> jComboBoxApuesta;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JPanel jPanelPista;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSliderVelocidad;
    // End of variables declaration//GEN-END:variables
}
